package autogateway

// ProviderParameters contains only fields generated by Auto for an upstream
// request. Client supplied reasoning fields are intentionally absent from
// this type so an adapter cannot accidentally forward them.
type ProviderParameters struct {
	Model              string
	Stream             bool
	Reasoning          EffortMapping
	ReasoningParameter map[string]any
}

// BuildProviderParameters maps the internal route decision to the provider's
// parameter shape. A target effort that the provider cannot express is
// defaulted by the adapter and produces no reasoning parameter.
func BuildProviderParameters(provider, protocol string, model Model, effort ReasoningEffort, stream bool) ProviderParameters {
	mapping := MapReasoningEffort(provider, protocol, effort, model.ReasoningEfforts)
	parameters := map[string]any{}
	if mapping.Status == EffortApplied || mapping.Status == EffortMapped {
		if mapping.Parameter == "reasoning.effort" {
			parameters["reasoning"] = map[string]any{"effort": string(mapping.Applied)}
		} else if mapping.Parameter == "output_config.effort" {
			parameters["output_config"] = map[string]any{"effort": string(mapping.Applied)}
		} else {
			parameters[mapping.Parameter] = string(mapping.Applied)
		}
	}
	return ProviderParameters{Model: model.Name, Stream: stream, Reasoning: mapping, ReasoningParameter: parameters}
}
