package autogateway

// ReasoningEffort is generated by Auto. It is never sourced from a client request.
type ReasoningEffort string

const (
	ReasoningNone    ReasoningEffort = "none"
	ReasoningMinimal ReasoningEffort = "minimal"
	ReasoningLow     ReasoningEffort = "low"
	ReasoningMedium  ReasoningEffort = "medium"
	ReasoningHigh    ReasoningEffort = "high"
	ReasoningXHigh   ReasoningEffort = "xhigh"
	ReasoningMax     ReasoningEffort = "max"
)

type EffortStatus string

const (
	EffortApplied     EffortStatus = "applied"
	EffortMapped      EffortStatus = "mapped"
	EffortUnsupported EffortStatus = "unsupported"
	EffortDefaulted   EffortStatus = "defaulted"
)

type EffortMapping struct {
	Requested ReasoningEffort
	Applied   ReasoningEffort
	Status    EffortStatus
	Parameter string
}

func InferReasoningEffort(score int) ReasoningEffort {
	switch {
	case score >= 90:
		return ReasoningXHigh
	case score >= 65:
		return ReasoningHigh
	case score >= 35:
		return ReasoningMedium
	case score >= 15:
		return ReasoningLow
	default:
		return ReasoningNone
	}
}

func modelSupportsReasoningEffort(model Model, effort ReasoningEffort) bool {
	if effort == "" || len(model.ReasoningEfforts) == 0 {
		return true
	}
	for _, supported := range model.ReasoningEfforts {
		if supported == effort {
			return true
		}
	}
	return false
}

// MapReasoningEffort converts Auto's canonical value to the provider parameter.
// The caller supplies the model's verified capability list; no client value is used.
func MapReasoningEffort(provider, protocol string, target ReasoningEffort, supported []ReasoningEffort) EffortMapping {
	parameter := "reasoning_effort"
	if canonicalProtocol(protocol) == "responses" {
		parameter = "reasoning.effort"
	}
	if target == "" {
		target = ReasoningNone
	}
	if canonicalProtocol(protocol) == "anthropic" {
		// The configured Sub2API Messages bridge ignores thinking.type and
		// defaults to medium when effort is absent. Send even none explicitly.
		// This is the bridge contract, not a native Claude capability claim.
		parameter = "output_config.effort"
	}
	// Match DeepSeek's documented aliases, not a numeric cross-vendor scale.
	if provider == "deepseek" {
		native := target
		switch target {
		case ReasoningMinimal:
			native = ReasoningLow
		case ReasoningMedium, ReasoningXHigh:
			native = ReasoningHigh
		}
		if native != target {
			for _, allowed := range supported {
				if allowed == native {
					return EffortMapping{Requested: target, Applied: native, Status: EffortMapped, Parameter: parameter}
				}
			}
		}
	}
	for _, value := range supported {
		if value == target {
			return EffortMapping{Requested: target, Applied: target, Status: EffortApplied, Parameter: parameter}
		}
	}
	// Use the nearest supported effort at or above the target. In particular,
	// Astra none/minimal map to low instead of sending an invalid value.
	order := []ReasoningEffort{ReasoningNone, ReasoningMinimal, ReasoningLow, ReasoningMedium, ReasoningHigh, ReasoningXHigh, ReasoningMax}
	for _, candidate := range order {
		if effortRank(candidate) < effortRank(target) {
			continue
		}
		for _, allowed := range supported {
			if candidate == allowed {
				return EffortMapping{Requested: target, Applied: candidate, Status: EffortMapped, Parameter: parameter}
			}
		}
	}
	for i := len(order) - 1; i >= 0; i-- {
		for _, allowed := range supported {
			if order[i] == allowed {
				return EffortMapping{Requested: target, Applied: allowed, Status: EffortMapped, Parameter: parameter}
			}
		}
	}

	return EffortMapping{Requested: target, Status: EffortDefaulted, Parameter: parameter}
}
