rules:
  - GEOSITE,category-ads-all,REJECT
  - DOMAIN,analytics.strava.com,REJECT
  - DOMAIN,app.adjust.com,REJECT
  - DOMAIN,app.appsflyer.com,REJECT
  - DOMAIN,chybenzun.top,DIRECT
  - DOMAIN,invite.linuxdo.org,DIRECT
  - DOMAIN,ip.istatmenus.app,DIRECT
  - DOMAIN,log.mmstat.com,REJECT
  - DOMAIN,muyuan.do,DIRECT
  - DOMAIN,origin-a.akamaihd.net,DIRECT
  - DOMAIN,sms.imagetasks.com,DIRECT
  - DOMAIN,speedtest.macpaw.com,DIRECT
  - DOMAIN,sycm.mmstat.com,DIRECT
  - DOMAIN-SUFFIX,baidustatic.com,DIRECT
  - DOMAIN-SUFFIX,comicat.org,DIRECT
  - DOMAIN-SUFFIX,feishu.com,DIRECT
  - DOMAIN-SUFFIX,jdimg.com,DIRECT
  - DOMAIN-SUFFIX,netspeedtestmaster.com,DIRECT
  - DOMAIN-SUFFIX,qqlivecdn.com,DIRECT
  - DOMAIN-SUFFIX,snssdk.com,DIRECT
  - DOMAIN-SUFFIX,download.jetbrains.com,DIRECT
  - DOMAIN-SUFFIX,download-cdn.jetbrains.com,DIRECT
  - DOMAIN-SUFFIX,update.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,windowsupdate.com,DIRECT
  - DOMAIN-SUFFIX,windowsupdate.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,delivery.mp.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,download.microsoft.com,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - DOMAIN,update.code.visualstudio.com,DIRECT
  - DOMAIN-SUFFIX,vscode-cdn.net,DIRECT
  - GEOSITE,microsoft,PROXY
  - GEOSITE,jetbrains,PROXY
  - GEOSITE,category-pt,PROXY
  - GEOSITE,private,DIRECT
  - GEOSITE,CN,DIRECT
  - IP-CIDR,8.216.44.189/32,DIRECT,no-resolve
  - IP-CIDR,47.251.166.27/32,DIRECT,no-resolve
  - IP-CIDR,106.14.254.110/32,DIRECT,no-resolve
  - IP-CIDR,179.253.245.229/32,DIRECT,no-resolve
  - IP-CIDR,203.205.238.0/23,DIRECT,no-resolve
  - IP-CIDR,203.205.254.0/23,DIRECT,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,PROXY
